### ISSUE TITLE
distributed map reduce?

### ISSUE THREAD

**Issue by chrislusf** [nmaquet/kasper#5]
I found your lib is pretty interesting and we share many similar ideas. Maybe we can collaborate somehow.

How about this distributed map reduce?

https://github.com/chrislusf/gleam/blob/master/examples/kafka_reader/kafka_reader.go

**Comment by nmaquet** [comment]
@chrislusf Thanks! I didn't know about Gleam and it looks really cool.

Kasper doesn't currently provide any declarative way of creating processing pipelines like Gleam does. I'd be keen to explore ways to define Kasper stream processors more declaratively. Kind of what Kafka Stream provides. Is this what you had in mind?
